# Generated by Django 3.2.10 on 2021-12-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
