# Generated by Django 3.2.10 on 2021-12-12 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='message',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.message'),
        ),
    ]
